// This file is generated by Cogent

#include <platsupport/plat/cogent_meson.h>

static inline void d5_set_timer_e_part0(t3 *b, unsigned int v)
{
    (*b).data[18U] = ((*b).data[18U] & ~(0XFFFFFFFFU << 0U)) | (0XFFFFFFFFU &
                                                                v) << 0U;
}
static inline void d4_set_timer_e(t3 *b, u32 v)
{
    d5_set_timer_e_part0(b, (unsigned int) (v >> 0U & 4294967295U));
}
static inline void d7_set_timer_e_hi_part0(t3 *b, unsigned int v)
{
    (*b).data[19U] = ((*b).data[19U] & ~(0XFFFFFFFFU << 0U)) | (0XFFFFFFFFU &
                                                                v) << 0U;
}
static inline void d6_set_timer_e_hi(t3 *b, u32 v)
{
    d7_set_timer_e_hi_part0(b, (unsigned int) (v >> 0U & 4294967295U));
}
static inline void d11_set_timer_a_input_clk_tag_part0(t3 *b, unsigned int v)
{
    (*b).data[0U] = ((*b).data[0U] & ~(0X3U << 0U)) | (0X3U & v) << 0U;
}
static inline void d10_set_timer_a_input_clk_tag(t3 *b, unsigned int v)
{
    d11_set_timer_a_input_clk_tag_part0(b, (unsigned int) (v >> 0U & 3U));
}
static inline void d12_set_timer_a_input_clk_TIMEOUT_TIMEBASE_100_US(t3 *b,
                                                                     unit_t v)
{ }
static inline void d13_set_timer_a_input_clk_TIMEOUT_TIMEBASE_10_US(t3 *b,
                                                                    unit_t v)
{ }
static inline void d14_set_timer_a_input_clk_TIMEOUT_TIMEBASE_1_MS(t3 *b,
                                                                   unit_t v)
{ }
static inline void d15_set_timer_a_input_clk_TIMEOUT_TIMEBASE_1_US(t3 *b,
                                                                   unit_t v)
{ }
static inline void d9_set_timer_a_input_clk(t3 *b, t1 v)
{
    if (v.tag == TAG_ENUM_TIMEOUT_TIMEBASE_1_US) {
        d10_set_timer_a_input_clk_tag(b, 0U);
        d15_set_timer_a_input_clk_TIMEOUT_TIMEBASE_1_US(b,
                                                        v.TIMEOUT_TIMEBASE_1_US);
    } else if (v.tag == TAG_ENUM_TIMEOUT_TIMEBASE_1_MS) {
        d10_set_timer_a_input_clk_tag(b, 3U);
        d14_set_timer_a_input_clk_TIMEOUT_TIMEBASE_1_MS(b,
                                                        v.TIMEOUT_TIMEBASE_1_MS);
    } else if (v.tag == TAG_ENUM_TIMEOUT_TIMEBASE_10_US) {
        d10_set_timer_a_input_clk_tag(b, 1U);
        d13_set_timer_a_input_clk_TIMEOUT_TIMEBASE_10_US(b,
                                                         v.TIMEOUT_TIMEBASE_10_US);
    } else {
        d10_set_timer_a_input_clk_tag(b, 2U);
        d12_set_timer_a_input_clk_TIMEOUT_TIMEBASE_100_US(b,
                                                          v.TIMEOUT_TIMEBASE_100_US);
    }
}
static inline void d18_set_timer_e_input_clk_tag_part0(t3 *b, unsigned int v)
{
    (*b).data[0U] = ((*b).data[0U] & ~(0X7U << 8U)) | (0X7U & v) << 8U;
}
static inline void d17_set_timer_e_input_clk_tag(t3 *b, unsigned int v)
{
    d18_set_timer_e_input_clk_tag_part0(b, (unsigned int) (v >> 0U & 7U));
}
static inline void d19_set_timer_e_input_clk_TIMESTAMP_TIMEBASE_100_US(t3 *b,
                                                                       unit_t v)
{ }
static inline void d20_set_timer_e_input_clk_TIMESTAMP_TIMEBASE_10_US(t3 *b,
                                                                      unit_t v)
{ }
static inline void d21_set_timer_e_input_clk_TIMESTAMP_TIMEBASE_1_MS(t3 *b,
                                                                     unit_t v)
{ }
static inline void d22_set_timer_e_input_clk_TIMESTAMP_TIMEBASE_1_US(t3 *b,
                                                                     unit_t v)
{ }
static inline void d23_set_timer_e_input_clk_TIMESTAMP_TIMEBASE_SYSTEM(t3 *b,
                                                                       unit_t v)
{ }
static inline void d16_set_timer_e_input_clk(t3 *b, t2 v)
{
    if (v.tag == TAG_ENUM_TIMESTAMP_TIMEBASE_SYSTEM) {
        d17_set_timer_e_input_clk_tag(b, 0U);
        d23_set_timer_e_input_clk_TIMESTAMP_TIMEBASE_SYSTEM(b,
                                                            v.TIMESTAMP_TIMEBASE_SYSTEM);
    } else if (v.tag == TAG_ENUM_TIMESTAMP_TIMEBASE_1_US) {
        d17_set_timer_e_input_clk_tag(b, 1U);
        d22_set_timer_e_input_clk_TIMESTAMP_TIMEBASE_1_US(b,
                                                          v.TIMESTAMP_TIMEBASE_1_US);
    } else if (v.tag == TAG_ENUM_TIMESTAMP_TIMEBASE_1_MS) {
        d17_set_timer_e_input_clk_tag(b, 4U);
        d21_set_timer_e_input_clk_TIMESTAMP_TIMEBASE_1_MS(b,
                                                          v.TIMESTAMP_TIMEBASE_1_MS);
    } else if (v.tag == TAG_ENUM_TIMESTAMP_TIMEBASE_10_US) {
        d17_set_timer_e_input_clk_tag(b, 2U);
        d20_set_timer_e_input_clk_TIMESTAMP_TIMEBASE_10_US(b,
                                                           v.TIMESTAMP_TIMEBASE_10_US);
    } else {
        d17_set_timer_e_input_clk_tag(b, 3U);
        d19_set_timer_e_input_clk_TIMESTAMP_TIMEBASE_100_US(b,
                                                            v.TIMESTAMP_TIMEBASE_100_US);
    }
}
static inline unsigned int d25_get_timer_e_hi_part0(t3 *b)
{
    return (*b).data[19U] >> 0U & 0XFFFFFFFFU;
}
static inline u32 d24_get_timer_e_hi(t3 *b)
{
    return (u32) d25_get_timer_e_hi_part0(b) << 0U;
}
static inline unsigned int d27_get_timer_e_part0(t3 *b)
{
    return (*b).data[18U] >> 0U & 0XFFFFFFFFU;
}
static inline u32 d26_get_timer_e(t3 *b)
{
    return (u32) d27_get_timer_e_part0(b) << 0U;
}
static inline void d30_set_timer_a_mode_part0(t3 *b, unsigned int v)
{
    (*b).data[0U] = ((*b).data[0U] & ~(0X1U << 11U)) | (0X1U & v) << 11U;
}
static inline void d29_set_timer_a_mode(t3 *b, bool_t v)
{
    d30_set_timer_a_mode_part0(b, (unsigned int) (v.boolean >> 0U & 1U));
}
static inline void d32_set_timer_a_part0(t3 *b, unsigned int v)
{
    (*b).data[1U] = ((*b).data[1U] & ~(0XFFFFFFFFU << 0U)) | (0XFFFFFFFFU &
                                                              v) << 0U;
}
static inline void d31_set_timer_a(t3 *b, u32 v)
{
    d32_set_timer_a_part0(b, (unsigned int) (v >> 0U & 4294967295U));
}
static inline void d34_set_timer_a_en_part0(t3 *b, unsigned int v)
{
    (*b).data[0U] = ((*b).data[0U] & ~(0X1U << 15U)) | (0X1U & v) << 15U;
}
static inline void d33_set_timer_a_en(t3 *b, bool_t v)
{
    d34_set_timer_a_en_part0(b, (unsigned int) (v.boolean >> 0U & 1U));
}
static inline unsigned int d36_get_timer_a_en_part0(t3 *b)
{
    return (*b).data[0U] >> 15U & 0X1U;
}
static inline bool_t d35_get_timer_a_en(t3 *b)
{
    return (bool_t) {.boolean = (unsigned char) d36_get_timer_a_en_part0(b) <<
                     0U};
}
static inline unsigned int d38_get_timer_a_part0(t3 *b)
{
    return (*b).data[1U] >> 0U & 0XFFFFFFFFU;
}
static inline u32 d37_get_timer_a(t3 *b)
{
    return (u32) d38_get_timer_a_part0(b) << 0U;
}
static inline unsigned int d40_get_timer_a_mode_part0(t3 *b)
{
    return (*b).data[0U] >> 11U & 0X1U;
}
static inline bool_t d39_get_timer_a_mode(t3 *b)
{
    return (bool_t) {.boolean = (unsigned char) d40_get_timer_a_mode_part0(b) <<
                     0U};
}
static inline unsigned int d43_get_timer_a_input_clk_tag_part0(t3 *b)
{
    return (*b).data[0U] >> 0U & 0X3U;
}
static inline unsigned int d42_get_timer_a_input_clk_tag(t3 *b)
{
    return (unsigned int) d43_get_timer_a_input_clk_tag_part0(b) << 0U;
}
static inline unit_t d44_get_timer_a_input_clk_TIMEOUT_TIMEBASE_100_US(t3 *b)
{
    return (unit_t) {.dummy = 0};
}
static inline unit_t d45_get_timer_a_input_clk_TIMEOUT_TIMEBASE_10_US(t3 *b)
{
    return (unit_t) {.dummy = 0};
}
static inline unit_t d46_get_timer_a_input_clk_TIMEOUT_TIMEBASE_1_MS(t3 *b)
{
    return (unit_t) {.dummy = 0};
}
static inline unit_t d47_get_timer_a_input_clk_TIMEOUT_TIMEBASE_1_US(t3 *b)
{
    return (unit_t) {.dummy = 0};
}
static inline t1 d41_get_timer_a_input_clk(t3 *b)
{
    return d42_get_timer_a_input_clk_tag(b) == 0U ? (t1) {.tag =
                                                          TAG_ENUM_TIMEOUT_TIMEBASE_1_US,
                                                          .TIMEOUT_TIMEBASE_1_US =
                                                          d47_get_timer_a_input_clk_TIMEOUT_TIMEBASE_1_US(b)} : d42_get_timer_a_input_clk_tag(b) ==
        3U ? (t1) {.tag = TAG_ENUM_TIMEOUT_TIMEBASE_1_MS,
                   .TIMEOUT_TIMEBASE_1_MS =
                   d46_get_timer_a_input_clk_TIMEOUT_TIMEBASE_1_MS(b)} : d42_get_timer_a_input_clk_tag(b) ==
        1U ? (t1) {.tag = TAG_ENUM_TIMEOUT_TIMEBASE_10_US,
                   .TIMEOUT_TIMEBASE_10_US =
                   d45_get_timer_a_input_clk_TIMEOUT_TIMEBASE_10_US(b)} : (t1) {.tag =
                                                                                TAG_ENUM_TIMEOUT_TIMEBASE_100_US,
                                                                                .TIMEOUT_TIMEBASE_100_US =
                                                                                d44_get_timer_a_input_clk_TIMEOUT_TIMEBASE_100_US(b)};
}
static inline unsigned int d50_get_timer_e_input_clk_tag_part0(t3 *b)
{
    return (*b).data[0U] >> 8U & 0X7U;
}
static inline unsigned int d49_get_timer_e_input_clk_tag(t3 *b)
{
    return (unsigned int) d50_get_timer_e_input_clk_tag_part0(b) << 0U;
}
static inline unit_t d51_get_timer_e_input_clk_TIMESTAMP_TIMEBASE_100_US(t3 *b)
{
    return (unit_t) {.dummy = 0};
}
static inline unit_t d52_get_timer_e_input_clk_TIMESTAMP_TIMEBASE_10_US(t3 *b)
{
    return (unit_t) {.dummy = 0};
}
static inline unit_t d53_get_timer_e_input_clk_TIMESTAMP_TIMEBASE_1_MS(t3 *b)
{
    return (unit_t) {.dummy = 0};
}
static inline unit_t d54_get_timer_e_input_clk_TIMESTAMP_TIMEBASE_1_US(t3 *b)
{
    return (unit_t) {.dummy = 0};
}
static inline unit_t d55_get_timer_e_input_clk_TIMESTAMP_TIMEBASE_SYSTEM(t3 *b)
{
    return (unit_t) {.dummy = 0};
}
static inline t2 d48_get_timer_e_input_clk(t3 *b)
{
    return d49_get_timer_e_input_clk_tag(b) == 0U ? (t2) {.tag =
                                                          TAG_ENUM_TIMESTAMP_TIMEBASE_SYSTEM,
                                                          .TIMESTAMP_TIMEBASE_SYSTEM =
                                                          d55_get_timer_e_input_clk_TIMESTAMP_TIMEBASE_SYSTEM(b)} : d49_get_timer_e_input_clk_tag(b) ==
        1U ? (t2) {.tag = TAG_ENUM_TIMESTAMP_TIMEBASE_1_US,
                   .TIMESTAMP_TIMEBASE_1_US =
                   d54_get_timer_e_input_clk_TIMESTAMP_TIMEBASE_1_US(b)} : d49_get_timer_e_input_clk_tag(b) ==
        4U ? (t2) {.tag = TAG_ENUM_TIMESTAMP_TIMEBASE_1_MS,
                   .TIMESTAMP_TIMEBASE_1_MS =
                   d53_get_timer_e_input_clk_TIMESTAMP_TIMEBASE_1_MS(b)} : d49_get_timer_e_input_clk_tag(b) ==
        2U ? (t2) {.tag = TAG_ENUM_TIMESTAMP_TIMEBASE_10_US,
                   .TIMESTAMP_TIMEBASE_10_US =
                   d52_get_timer_e_input_clk_TIMESTAMP_TIMEBASE_10_US(b)} : (t2) {.tag =
                                                                                  TAG_ENUM_TIMESTAMP_TIMEBASE_100_US,
                                                                                  .TIMESTAMP_TIMEBASE_100_US =
                                                                                  d51_get_timer_e_input_clk_TIMESTAMP_TIMEBASE_100_US(b)};
}
static inline t3 *reset_timer_e(t3 *a1)
{
    t3 *r2 = a1;
    u32 r3 = 0U;
    t3 *r4 = r2;

    d4_set_timer_e(r4, r3);

    t3 *r5 = r4;
    u32 r6 = 0U;
    t3 *r7 = r5;

    d6_set_timer_e_hi(r7, r6);

    t3 *r8 = r7;

    return r8;
}
static inline t8 *initialize(t8 *a1)
{
    t3 *r2 = (*a1).regs;
    unit_t r3 = (unit_t) {.dummy = 0};
    t1 r4;

    r4 = (t1) {.tag = TAG_ENUM_TIMEOUT_TIMEBASE_1_MS, .TIMEOUT_TIMEBASE_1_MS =
               r3};

    t1 r5 = r4;
    t1 r6 = r5;
    t3 *r7 = r2;

    d9_set_timer_a_input_clk(r7, r6);

    t3 *r8 = r7;
    unit_t r9 = (unit_t) {.dummy = 0};
    t2 r10;

    r10 = (t2) {.tag = TAG_ENUM_TIMESTAMP_TIMEBASE_1_US,
                .TIMESTAMP_TIMEBASE_1_US = r9};

    t2 r11 = r10;
    t2 r12 = r11;
    t3 *r13 = r8;

    d16_set_timer_e_input_clk(r13, r12);

    t3 *r14 = r13;
    t3 *r15 = reset_timer_e(r14);
    t8 *r16 = a1;

    (*r16).regs = r15;

    t8 *r17 = r16;

    return r17;
}
static inline u64 meson_get_time(t8 *a1)
{
    t8 *r2 = a1;
    t3 *r3 = (*r2).regs;
    u32 r4 = d24_get_timer_e_hi(r3);
    u64 r5 = (u64) r4;
    t3 *r6 = (*r2).regs;
    u32 r7 = d26_get_timer_e(r6);
    u64 r8 = (u64) r7;
    t3 *r9 = (*r2).regs;
    u32 r10 = d24_get_timer_e_hi(r9);
    u64 r11 = (u64) r10;
    bool_t r12 = (bool_t) {.boolean = r11 != r5};
    u64 r13;

    if (r12.boolean) {
        t3 *r14 = (*r2).regs;
        u32 r15 = d26_get_timer_e(r14);
        u64 r16 = (u64) r15;
        u64 r17 = 32U;
        u64 r18 = r17 >= 64U ? 0U : r11 << r17;
        u64 r19 = r18 | r16;
        u64 r20 = 1000U;
        u64 r21 = r19 * r20;

        r13 = r21;
    } else {
        u64 r22 = r8;
        u64 r23 = 32U;
        u64 r24 = r23 >= 64U ? 0U : r11 << r23;
        u64 r25 = r24 | r22;
        u64 r26 = 1000U;
        u64 r27 = r25 * r26;

        r13 = r27;
    }

    u64 r28 = r13;

    return r28;
}
static inline t8 *meson_set_timeout(t28 a1)
{
    t8 *r2 = a1.p1;
    u16 r3 = a1.p2;
    bool_t r4 = a1.p3;
    t3 *r5 = (*r2).regs;
    t3 *r6 = r5;

    d29_set_timer_a_mode(r6, r4);

    t3 *r7 = r6;
    u32 r8 = (u32) r3;
    t3 *r9 = r7;

    d31_set_timer_a(r9, r8);

    t3 *r10 = r9;
    bool_t r11;

    if (LETBANG_TRUE) {
        r11 = (*r2).disable;
    } else
        ;

    t8 *r12;

    if (r11.boolean) {
        bool_t r13 = (bool_t) {.boolean = 1U};
        t3 *r14 = r10;

        d33_set_timer_a_en(r14, r13);

        t3 *r15 = r14;
        t8 *r16 = r2;

        (*r16).regs = r15;

        t8 *r17 = r16;
        bool_t r18 = (bool_t) {.boolean = 0U};
        t8 *r19 = r17;

        (*r19).disable = r18;
        r12 = r19;
    } else {
        t8 *r20 = r2;

        (*r20).regs = r10;
        r12 = r20;
    }

    t8 *r21 = r12;

    return r21;
}
static inline t8 *meson_stop_timer(t8 *a1)
{
    t3 *r2 = (*a1).regs;
    bool_t r3 = (bool_t) {.boolean = 0U};
    t3 *r4 = r2;

    d33_set_timer_a_en(r4, r3);

    t3 *r5 = r4;
    t8 *r6 = a1;

    (*r6).regs = r5;

    t8 *r7 = r6;
    bool_t r8 = (bool_t) {.boolean = 1U};
    t8 *r9 = r7;

    (*r9).disable = r8;

    t8 *r10 = r9;

    return r10;
}
